name: BetterTeamsAddon
version: 1.0.0
main: dev.allenalt.betterteamsaddon.BetterTeamsAddon
api-version: 1.21
author: Dev_Allenalt_tw
depend: [BetterTeams]
description: Addon for BetterTeams that opens a custom menu when creating a team.
