name: Build BetterTeamsAddon

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # ✅ Install BetterTeams locally
      - name: Install BetterTeams dependency
        run: mvn install:install-file -Dfile=libs/BetterTeams-4.15.2.jar -DgroupId=com.booksaw.betterTeams -DartifactId=BetterTeams -Dversion=4.15.2 -Dpackaging=jar

      - name: Build with Maven
        run: mvn -B clean package

      - name: Upload plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: BetterTeamsAddon
          path: target/*.jar
